### ISSUE TITLE
Unauthorized (HTTP 401). Failed to get an access token.

### ISSUE THREAD

**Issue by analytics-ml** [cloudyr/bigQueryR#45]
I encounter the following error while authentication with Google.  (_bqr_auth()_ )

_Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
  Unauthorized (HTTP 401). Failed to get an access token.
In addition: Warning message:
In googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  :
  travis_environment_var argument is now unsupported and does nothing_

it was working perfectly before updating the package to version 0.3.2. 

Other libraries like bigrquery authenticate perfectly but not bigQueryR.

Where is the problem any suggestions?

**Comment by MarkEdmondson1234** [comment]
Could you report your sessionInfo() ? I suspect it’s you need to update to googleAuthR 0.6.2. If that’s installed please try reauthenticate with a fresh session.

**Comment by analytics-ml** [comment]
sessioninfo()

**Comment by MarkEdmondson1234** [comment]
May I ask for the code you are using to authenticate?  Are you using your own client ID/secret?

**Comment by MarkEdmondson1234** [comment]
Ok I could replicate it.

Short term I suggest you authenticate via the service JSON method, which involves downloading the auth.json and then placing it in the environment argument `BQ_AUTH_FILE` - this authentication is functioning normally.  There are some details here: http://code.markedmondson.me/googleAuthR/articles/google-authentication-types.html#authentication-with-a-json-file-via-service-accounts

Long term I will fix this, which is caused by the scopes changing during authentication when using the `bq_auth()` function.

**Comment by MarkEdmondson1234** [comment]
I think this is due to my default bigQueryR project not being verified e.g. it works if you set your own client ID and secret via `googleAuthR::gar_set_client()`  and similar.

**Comment by analytics-ml** [comment]
i was using bqr_auth() for authenticate
job<-bqr_upload_data(projectId = "xyz", 
                datasetId = "test_dataset", 
                tableId="test_table",
                upload_data = head(df)
)

**Comment by analytics-ml** [comment]
Thank you for the suggesting JSON method. It worked.
I also want to mention that **wait = FALSE** argument in bqr_upload_data() doesn't return and waits for the job to complete. (it wait till the entire dataset is uploaded.)
where am I doing wrong?

I want to upload a dataset of around 1 Million rows and 39 columns to big query daily(without using google cloud. Or cloud is the only option?).

**Comment by MarkEdmondson1234** [comment]
Cool, I think the answer here for now is to configure using your own Google Cloud project, since the bigQueryR doesn't work at the moment.  I'll answer your follow up question in another issue to keep this one clean.

**Comment by MarkEdmondson1234** [comment]
See https://github.com/cloudyr/bigQueryR/issues/47

**Comment by MarkEdmondson1234** [comment]
Related? https://github.com/r-dbi/bigrquery/issues/182

**Comment by MarkEdmondson1234** [comment]
@analytics-ml @peteratemarsys the original bigQueryR Google project has been verified now, so I think it should work again as before using the CRAN version?  Can anyone confirm?  In any case, the GitHub version works for me using the bigQueryR Google project.

**Comment by peteratemarsys** [comment]
@MarkEdmondson1234 It still doesn't work with the CRAN version. I uninstalled and then re-installed the package to make sure and got the same error message. I then tried too with the GitHub version and that works just fine.

**Comment by peteratemarsys** [comment]
Hi @MarkEdmondson1234 ! Do you plan to pick this up again? I tried it using the CRAN version again and can confirm that using email authentication doesn't work. I'm asking because in our project we would sometimes need to use service key authentication (e.g. running services on a server) but sometimes it'd be more convenient to use the email authentication for personal analysis.

**Comment by MarkEdmondson1234** [comment]
Hi  @peteratemarsys are you saying it works with the GitHub version?  In that case I will just make sure to publish that to CRAN ASAP

**Comment by peteratemarsys** [comment]
Hi @MarkEdmondson1234! Yes, it works with the GitHub version. Many thanks
